#include <Wire.h> // [cite: 1]
#include <Adafruit_GFX.h> // [cite: 1]
#include <Adafruit_SH110X.h>  // [cite: 1]
#include <SPI.h> // [cite: 1]
#include <MFRC522.h> // [cite: 1]
#include <WiFiS3.h>  // [cite: 1]
#include <WiFiUdp.h> // [cite: 1]
#include <NTPClient.h> // [cite: 1]
#include <EEPROM.h> // [cite: 1]
#include "RTC.h" // [cite: 1]
#include <ArduinoOTA.h>  // [cite: 1]

const char* app_version = "v2.9.4"; // [cite: 1]

struct User { // [cite: 2]
  byte uid[4]; // [cite: 2]
  char name[16];  // [cite: 2]
}; // [cite: 2]

struct LogEntry {  // [cite: 2]
  String time;  // [cite: 2]
  String msg;  // [cite: 2]
}; // [cite: 2]

String getFormattedSystemTime(); // [cite: 3]
void addLog(String msg); // [cite: 3]
void openDoor(String source); // [cite: 3]
void forceHardwareRFIDReset(); // [cite: 3]
void displayProvisioningInstructions(String errorContext = ""); // [cite: 3]
void saveConfiguration(String newSSID, String newPass, String newAdmin, String newTeleIP, int newTelePort, bool enableTele); // [cite: 4]
void factoryResetSettings(); // [cite: 4]
void loadConfiguration(); // [cite: 4]
void loadCards(); // [cite: 4]
void saveNewCard(byte* uid, String nameStr); // [cite: 5]
void deleteUser(int index); // [cite: 5]
void updateDisplay(String status, String info = ""); // [cite: 5]
void renderSystemUI(); // [cite: 5]
void handleProvisioningServer(); // [cite: 5]
void handleWebServer(); // [cite: 6]
void handleOnlineInstallerServer(); // [cite: 6]
void executeCloudSynchronization(); // [cite: 6]
void transmitCardPayloadToCloud(String uidStr, byte* rawUid, bool runRegister); // [cite: 6]
void sendExternalTelemetry(String logData); // [cite: 6]
String urlDecode(String str); // [cite: 6]
String urlEncode(String str); // [cite: 6]

String urlEncode(String str) { // [cite: 6]
  String encoded = ""; // [cite: 7]
  char c; // [cite: 7]
  char hex[3]; // [cite: 7]
  for (unsigned int i = 0; i < str.length(); i++) { // [cite: 8]
    c = str[i]; // [cite: 8]
    if (isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') { // [cite: 9]
      encoded += c; // [cite: 9]
    } else if (c == ' ') { // [cite: 10]
      encoded += '+'; // [cite: 10]
    } else { // [cite: 11]
      sprintf(hex, "%%%02X", c); // [cite: 11]
      encoded += hex; // [cite: 11]
    } // [cite: 11]
  } // [cite: 8]
  return encoded; // [cite: 11]
} // [cite: 12]

char ssid[32] = ""; // [cite: 12]         
char pass[32] = ""; // [cite: 12]     
char admin_password[16] = ""; // [cite: 12]       
char proxmox_log_server[64] = "";  // [cite: 12]
int proxmox_log_port = 3000; // [cite: 12]
bool telemetryEnabled = false; // [cite: 13]

char temporary_password[8] = ""; // [cite: 13]
bool hasTemporaryPassword = false; // [cite: 13]

#define RELAY_PIN 4 // [cite: 14]
#define BUTTON_PIN 5 // [cite: 14]
#define LED_GREEN 7  // [cite: 14]
#define LED_RED 6 // [cite: 14]   
#define BUZZER_PIN 8 // [cite: 14]
#define RST_PIN 9 // [cite: 14]
#define SS_PIN 10 // [cite: 14]

#define MAX_LOGS 30  // [cite: 14]
#define OLED_RESET -1  // [cite: 14]

Adafruit_SH1106G display = Adafruit_SH1106G(128, 64, &Wire, OLED_RESET); // [cite: 14]
MFRC522 rfid(SS_PIN, RST_PIN); // [cite: 15]
WiFiUDP ntpUDP; // [cite: 15]
NTPClient timeClient(ntpUDP, "europe.pool.ntp.org", 7200);  // [cite: 15]
WiFiServer server(80);  // [cite: 15]

bool doorOpen = false; // [cite: 15]
bool learningMode = false; // [cite: 15]
bool autoExitLearn = false;  // [cite: 16]
bool provisioningMode = false;  // [cite: 16]
bool isOfflineStandby = false;  // [cite: 16]
bool hasSavedConfig = false; // [cite: 16]
User users[10]; // [cite: 16]
bool isCardActive[10] = {true, true, true, true, true, true, true, true, true, true};  // [cite: 17]
int totalCards = 0; // [cite: 17]
String pendingUsername = "Nowy Uzytkownik";  // [cite: 18]
String globalDisplayInfo = "";  // [cite: 18]

LogEntry lastActions[MAX_LOGS];  // [cite: 18]
int logCount = 0; // [cite: 18]

int failedLoginAttempts = 0; // [cite: 18]
unsigned long lockoutEndTime = 0; // [cite: 19]
unsigned long accessEndTime = 0; // [cite: 19]
bool rfidResetPending = false; // [cite: 19]
unsigned long lastScanTime = 0; // [cite: 19]
unsigned long lastWifiRetryTime = 0;  // [cite: 20]
unsigned long lastRfidWatchdogTime = 0;  // [cite: 20]
unsigned long lastPollTime = 0; // [cite: 20]
unsigned long lastSuccessfulPollTime = 0; // [cite: 20]
int globalAnimFrame = 0; // [cite: 21]
unsigned long lastFrameTick = 0; // [cite: 21]

String urlDecode(String str) { // [cite: 21]
  String decoded = ""; // [cite: 21]
  char ch; // [cite: 21]
  int i = 0; // [cite: 22]
  while (i < str.length()) { // [cite: 22]
    if (str[i] == '+') { // [cite: 22]
      decoded += ' '; // [cite: 22]
      i++; // [cite: 23]
    } else if (str[i] == '%') { // [cite: 23]
      if (i + 2 < str.length()) { // [cite: 23]
        char high = str[i+1]; // [cite: 23]
        char low = str[i+2]; // [cite: 24]
        int value = 0; // [cite: 24]
        if (high >= '0' && high <= '9') value += (high - '0') * 16; // [cite: 24]
        else if (high >= 'A' && high <= 'F') value += (high - 'A' + 10) * 16; // [cite: 25]
        else if (high >= 'a' && high <= 'f') value += (high - 'a' + 10) * 16; // [cite: 26]
        if (low >= '0' && low <= '9') value += (low - '0'); // [cite: 27]
        else if (low >= 'A' && low <= 'F') value += (low - 'A' + 10); // [cite: 28]
        else if (low >= 'a' && low <= 'f') value += (low - 'a' + 10); // [cite: 29]
        decoded += (char)value; // [cite: 29]
        i += 3; // [cite: 30]
      } else { // [cite: 30]
        decoded += '%'; // [cite: 30]
        i++; // [cite: 30]
      } // [cite: 31]
    } else { // [cite: 31]
      decoded += str[i]; // [cite: 31]
      i++; // [cite: 32]
    } // [cite: 32]
  } // [cite: 22]
  return decoded; // [cite: 32]
} // [cite: 32]

void loadConfiguration() { // [cite: 32]
  if (EEPROM.read(250) == 0x55) { // [cite: 32]
    EEPROM.get(260, ssid); // [cite: 32]
    EEPROM.get(292, pass); // [cite: 33]
    EEPROM.get(324, admin_password); // [cite: 33]
    EEPROM.get(340, proxmox_log_server); // [cite: 33]
    EEPROM.get(404, proxmox_log_port); // [cite: 33]
    telemetryEnabled = (EEPROM.read(251) == 0x01); // [cite: 33]
    provisioningMode = false;  // [cite: 33]
    hasSavedConfig = true; // [cite: 33]
  } else { // [cite: 34]
    provisioningMode = true;  // [cite: 34]
    hasSavedConfig = false; // [cite: 34]
    strcpy(admin_password, "admin"); // [cite: 34]
    strcpy(proxmox_log_server, "192.168.0.200"); // [cite: 34]
    proxmox_log_port = 3000; // [cite: 34]
  } // [cite: 35]
} // [cite: 35]

void saveConfiguration(String newSSID, String newPass, String newAdmin, String newTeleIP, int newTelePort, bool enableTele) { // [cite: 35]
  newSSID.toCharArray(ssid, 32); // [cite: 35]
  newPass.toCharArray(pass, 32); // [cite: 35]
  newAdmin.toCharArray(admin_password, 16); // [cite: 36]
  newTeleIP.toCharArray(proxmox_log_server, 64); // [cite: 36]
  proxmox_log_port = newTelePort; // [cite: 36]
  telemetryEnabled = enableTele; // [cite: 36]
  EEPROM.put(260, ssid); // [cite: 36]
  EEPROM.put(292, pass); // [cite: 36]
  EEPROM.put(324, admin_password); // [cite: 36]
  EEPROM.put(340, proxmox_log_server); // [cite: 36]
  EEPROM.put(404, proxmox_log_port); // [cite: 36]
  EEPROM.write(251, telemetryEnabled ? 0x01 : 0x00); // [cite: 37]
  EEPROM.write(250, 0x55);  // [cite: 37]
  hasTemporaryPassword = false; // [cite: 37]
  memset(temporary_password, 0, sizeof(temporary_password)); // [cite: 37]
} // [cite: 38]

void factoryResetSettings() { // [cite: 38]
  for (int i = 0; i < 512; i++) { // [cite: 38]
    EEPROM.write(i, 0xFF); // [cite: 38]
  } // [cite: 39]
  EEPROM.put(0, 0);  // [cite: 39]
} // [cite: 39]

void loadCards() { // [cite: 39]
  EEPROM.get(0, totalCards); // [cite: 39]
  if (totalCards < 0 || totalCards > 10) { // [cite: 40]
    totalCards = 0; // [cite: 40]
  } // [cite: 41]
  for (int i = 0; i < totalCards; i++) { // [cite: 41]
    EEPROM.get(10 + (i * sizeof(User)), users[i]); // [cite: 41]
    isCardActive[i] = (EEPROM.read(220 + i) != 0x00);  // [cite: 42]
  } // [cite: 42]
} // [cite: 42]

void saveNewCard(byte* uid, String nameStr) { // [cite: 42]
  if (totalCards >= 10) return; // [cite: 42]
  memset(&users[totalCards], 0, sizeof(User)); // [cite: 43]
  memcpy(users[totalCards].uid, uid, 4); // [cite: 43]
  nameStr.toCharArray(users[totalCards].name, 16); // [cite: 43]
  EEPROM.put(10 + (totalCards * sizeof(User)), users[totalCards]); // [cite: 43]
  isCardActive[totalCards] = true; // [cite: 43]
  EEPROM.write(220 + totalCards, 0x01); // [cite: 44]
  totalCards++; // [cite: 44]
  EEPROM.put(0, totalCards); // [cite: 44]
} // [cite: 44]

void deleteUser(int index) { // [cite: 44]
  if (index < 0 || index >= totalCards) return; // [cite: 44]
  for (int i = index; i < totalCards - 1; i++) { // [cite: 45]
    users[i] = users[i + 1]; // [cite: 45]
    EEPROM.put(10 + (i * sizeof(User)), users[i]); // [cite: 46]
    isCardActive[i] = isCardActive[i + 1];  // [cite: 46]
    EEPROM.write(220 + i, isCardActive[i] ? 0x01 : 0x00); // [cite: 46]
  } // [cite: 47]
  isCardActive[totalCards - 1] = true; // [cite: 47]
  EEPROM.write(220 + totalCards - 1, 0x01); // [cite: 47]
  totalCards--; // [cite: 47]
  EEPROM.put(0, totalCards); // [cite: 48]
} // [cite: 48]

void forceHardwareRFIDReset() { // [cite: 48]
  digitalWrite(RST_PIN, LOW); // [cite: 48]
  delay(30); // [cite: 48]
  digitalWrite(RST_PIN, HIGH); // [cite: 48]
  delay(30); // [cite: 48]
  rfid.PCD_Init();  // [cite: 48]
} // [cite: 48]

String getFormattedSystemTime() { // [cite: 48]
  RTCTime currentRTCTime; // [cite: 48]
  if (RTC.getTime(currentRTCTime)) { // [cite: 49]
    char timeBuffer[6]; // [cite: 49]
    sprintf(timeBuffer, "%02d:%02d", currentRTCTime.getHour(), currentRTCTime.getMinutes()); // [cite: 49]
    return String(timeBuffer); // [cite: 49]
  } // [cite: 49]
  return "--:--"; // [cite: 50]
} // [cite: 50]

void renderSystemUI() { // [cite: 50]
  display.clearDisplay(); // [cite: 50]
  display.setTextSize(1); // [cite: 50]
  display.setTextColor(SH110X_WHITE); // [cite: 50]
  display.setCursor(4, 2); // [cite: 50]
  display.print("SMART LOCK SYSTEM"); // [cite: 50]
  display.drawFastHLine(0, 12, 128, SH110X_WHITE); // [cite: 50]
  if (provisioningMode || isOfflineStandby) { // [cite: 51]
    display.setCursor(0, 18); // [cite: 51]
    display.println(globalDisplayInfo); // [cite: 51]
  }  // [cite: 52]
  else if (learningMode) { // [cite: 52]
    display.setCursor(20, 20); // [cite: 52]
    display.setTextSize(2); // [cite: 52]
    display.print("LEARNING"); // [cite: 52]
    display.setTextSize(1); // [cite: 52]
    display.setCursor(20, 42); // [cite: 52]
    display.print("Target: " + pendingUsername); // [cite: 53]
    int rippleRadius = 4 + (globalAnimFrame % 3) * 5; // [cite: 53]
    display.drawCircle(110, 32, rippleRadius, SH110X_WHITE); // [cite: 53]
    display.fillCircle(110, 32, 2, SH110X_WHITE); // [cite: 54]
  }  // [cite: 54]
  else if (doorOpen) { // [cite: 54]
    int shackleOffset = (globalAnimFrame > 4) ? 5 : globalAnimFrame; // [cite: 55] 
    display.fillRoundRect(14, 34, 22, 16, 2, SH110X_WHITE); // [cite: 55]
    display.fillCircle(25, 40, 2, SH110X_BLACK); // [cite: 55]
    display.drawFastVLine(25, 42, 4, SH110X_BLACK); // [cite: 55]
    display.drawCircleHelper(25, 34 - shackleOffset, 7, 1|2, SH110X_WHITE); // [cite: 56] 
    display.drawFastVLine(18, 34 - shackleOffset, 4, SH110X_WHITE);        // [cite: 56]
    display.setTextSize(2); // [cite: 56]
    display.setCursor(48, 20); // [cite: 56]
    display.print("OPEN"); // [cite: 56]
    display.setTextSize(1); // [cite: 56]
    display.setCursor(48, 40); // [cite: 56]
    display.print(globalDisplayInfo); // [cite: 57] 
    if (globalAnimFrame > 2) { // [cite: 57]
      int checkStage = min(globalAnimFrame - 2, 6); // [cite: 57]
      display.drawLine(100, 35, 100 + min(checkStage, 3), 35 + min(checkStage, 3), SH110X_WHITE); // [cite: 58]
      if (checkStage > 3) { // [cite: 59]
        display.drawLine(103, 38, 103 + (checkStage - 3) * 3, 38 - (checkStage - 3) * 3, SH110X_WHITE); // [cite: 59]
      } // [cite: 60]
    } // [cite: 60]
  }  // [cite: 60]
  else { // [cite: 60]
    display.fillRoundRect(14, 32, 22, 18, 2, SH110X_WHITE); // [cite: 60]
    display.fillCircle(25, 39, 2, SH110X_BLACK); // [cite: 61]
    display.drawFastVLine(25, 41, 5, SH110X_BLACK); // [cite: 61]
    display.drawCircleHelper(25, 32, 7, 1|2, SH110X_WHITE); // [cite: 61]
    display.drawFastVLine(18, 32, 4, SH110X_WHITE); // [cite: 61]
    display.drawFastVLine(32, 32, 4, SH110X_WHITE); // [cite: 62]
    display.setTextSize(2); // [cite: 62]
    display.setCursor(48, 24); // [cite: 62]
    display.print("LOCKED"); // [cite: 62]
  } // [cite: 62]

  display.drawFastHLine(0, 53, 128, SH110X_WHITE); // [cite: 62]
  display.setTextSize(1); // [cite: 62]
  display.setCursor(4, 56); // [cite: 62]
  if (WiFi.status() == WL_CONNECTED) { // [cite: 63]
    display.print(WiFi.localIP().toString()); // [cite: 63]
  } else if (isOfflineStandby) { // [cite: 63]
    display.print("AP: SETUP"); // [cite: 63]
  } else { // [cite: 64]
    display.print("DISCONNECTED"); // [cite: 64]
  } // [cite: 64]
  String liveTime = getFormattedSystemTime(); // [cite: 64]
  display.setCursor(94, 56); // [cite: 64]
  display.print(liveTime); // [cite: 64]
  display.display(); // [cite: 64]
} // [cite: 65]

void updateDisplay(String status, String info) { // [cite: 65]
  globalDisplayInfo = info; // [cite: 65]
  renderSystemUI(); // [cite: 65]
} // [cite: 66]

void displayProvisioningInstructions(String errorContext) { // [cite: 66]
  if (errorContext != "") { // [cite: 66]
    globalDisplayInfo = errorContext + "\nConnect to:\nSSID: ZAMEK_SETUP\nIP: 192.168.4.1"; // [cite: 66]
  } else { // [cite: 67]
    globalDisplayInfo = "INITIAL CONFIG!\nConnect to:\nSSID: ZAMEK_SETUP\nIP: 192.168.4.1"; // [cite: 67]
  } // [cite: 67]
  renderSystemUI(); // [cite: 67]
} // [cite: 68]

void sendExternalTelemetry(String logData) { // [cite: 68]
  if (!telemetryEnabled || WiFi.status() != WL_CONNECTED) return; // [cite: 68]
  WiFiClient telemetryClient; // [cite: 68]
  telemetryClient.setTimeout(150); // [cite: 68]
  if (telemetryClient.connect(proxmox_log_server, proxmox_log_port)) { // [cite: 69]
    telemetryClient.println("POST /log HTTP/1.1"); // [cite: 69]
    telemetryClient.print("Host: "); telemetryClient.println(proxmox_log_server); // [cite: 69]
    telemetryClient.println("Content-Type: text/plain; charset=utf-8"); // [cite: 69]
    telemetryClient.print("Content-Length: "); telemetryClient.println(logData.length()); // [cite: 69]
    telemetryClient.println("Connection: close\r\n"); // [cite: 70]
    telemetryClient.print(logData); // [cite: 70]
    telemetryClient.flush(); // [cite: 70]
    telemetryClient.stop(); // [cite: 70]
  } // [cite: 70]
} // [cite: 70]

void addLog(String msg) { // [cite: 70]
  RTCTime currentRTCTime; // [cite: 70]
  RTC.getTime(currentRTCTime); // [cite: 70]
  char timeBuffer[12]; // [cite: 70]
  sprintf(timeBuffer, "%02d:%02d:%02d", currentRTCTime.getHour(), currentRTCTime.getMinutes(), currentRTCTime.getSeconds()); // [cite: 70]
  String currentTime = String(timeBuffer); // [cite: 71]
  if (logCount < MAX_LOGS) { // [cite: 71]
    lastActions[logCount++] = {currentTime, msg}; // [cite: 71]
  } else { // [cite: 72]
    for (int i = 0; i < MAX_LOGS - 1; i++) { // [cite: 72]
      lastActions[i] = lastActions[i+1]; // [cite: 72]
    } // [cite: 73]
    lastActions[MAX_LOGS - 1] = {currentTime, msg}; // [cite: 73]
  } // [cite: 73]
  sendExternalTelemetry(msg); // [cite: 73]
} // [cite: 74]

void openDoor(String source) { // [cite: 74]
  doorOpen = true;  // [cite: 74]
  globalAnimFrame = 0;  // [cite: 74]
  accessEndTime = millis() + 3000; // [cite: 74]
  globalDisplayInfo = source; // [cite: 74]
  digitalWrite(RELAY_PIN, LOW); // [cite: 75]
  digitalWrite(LED_GREEN, HIGH); // [cite: 75]
  digitalWrite(LED_RED, LOW); // [cite: 75]
  tone(BUZZER_PIN, 1000, 200); // [cite: 75]
  addLog("Otwarto: " + source); // [cite: 75]
} // [cite: 76]

void handleProvisioningServer() { // [cite: 76]
  WiFiClient client = server.available(); // [cite: 76]
  if (!client) return; // [cite: 76]
  String reqHeader = ""; // [cite: 76]
  unsigned long webTimeout = millis() + 2000;  // [cite: 77]
  while (client.connected() && millis() < webTimeout) {  // [cite: 77]
    if (client.available()) { // [cite: 77]
      char c = client.read(); // [cite: 77]
      reqHeader += c; // [cite: 78]
      if (c == '\n') break;  // [cite: 78]
    } // [cite: 78]
  } // [cite: 78]
  while (client.available()) { client.read(); // [cite: 78]
  } // [cite: 79]
  addLog("REQ=" + reqHeader); // [cite: 79]

  if (reqHeader.indexOf("POST /save_setup") != -1 || reqHeader.indexOf("GET /save_setup") != -1) { // [cite: 79]
    int sIdx = reqHeader.indexOf("s=") + 2; // [cite: 79]
    int pIdx = reqHeader.indexOf("&p=") + 3; // [cite: 80]
    int aIdx = reqHeader.indexOf("&a=") + 3; // [cite: 80]
    int tiIdx = reqHeader.indexOf("&ti=") + 4; // [cite: 80]
    int tpIdx = reqHeader.indexOf("&tp=") + 4; // [cite: 81]
    int teIdx = reqHeader.indexOf("&te="); // [cite: 81]
    String rawSSID = reqHeader.substring(sIdx, reqHeader.indexOf("&p=")); // [cite: 81]
    String rawPass = reqHeader.substring(pIdx, reqHeader.indexOf("&a=")); // [cite: 81]
    String rawAdmin = reqHeader.substring(aIdx, reqHeader.indexOf("&ti=")); // [cite: 82]
    String rawTeleIP = reqHeader.substring(tiIdx, reqHeader.indexOf("&tp=")); // [cite: 82]
    int spacePos = reqHeader.indexOf(" ", tpIdx); // [cite: 82]
    int nextAmp = reqHeader.indexOf("&", tpIdx); // [cite: 83]
    int endPortPos = (nextAmp != -1 && nextAmp < spacePos) ? nextAmp : spacePos; // [cite: 83]
    String nTelePort = reqHeader.substring(tpIdx, endPortPos); // [cite: 84]
    bool runTele = (teIdx != -1); // [cite: 84]
    String decodedSSID = urlDecode(rawSSID); // [cite: 84]
    String decodedPass = urlDecode(rawPass); // [cite: 84]
    String decodedAdmin = urlDecode(rawAdmin); // [cite: 85]
    String decodedTeleIP = urlDecode(rawTeleIP); // [cite: 85]

    saveConfiguration(decodedSSID, decodedPass, decodedAdmin, decodedTeleIP, nTelePort.toInt(), runTele); // [cite: 85]
    client.println("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<html><body style='background:#121212;color:#fff;font-family:sans-serif;text-align:center;padding:50px;\'><h2>💾 Ustawienia Zapisane Pomyslnie!</h2></body></html>"); // [cite: 86]
    delay(50); client.stop(); // [cite: 86]
    tone(BUZZER_PIN, 2000, 800); // [cite: 86]
    delay(1000); // [cite: 86]
    NVIC_SystemReset();  // [cite: 86]
    return; // [cite: 86]
  } // [cite: 87]

  client.println("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: close\r\n"); // [cite: 87]
  client.println("<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>"); // [cite: 87]
  client.println("<style>body{background:#121212;color:#fff;font-family:sans-serif;padding:20px;} .box{background:#1e1e1e;padding:20px;border-radius:10px;max-width:400px;margin:20px auto;} input{display:block;width:92%;padding:12px;margin:12px auto;background:#2d2d2d;color:#fff;border:1px solid #444;border-radius:6px;}</style></head><body>"); // [cite: 87]
  client.println("<h2 style='text-align:center;'>⚙       Installer Setup Panel</h2><div class='box'><form method='GET' action='/save_setup'>"); // [cite: 88]
  client.println("<input type='text' name='s' value='" + String(ssid) + "' placeholder='SSID Wi-Fi' required>"); // [cite: 89]
  client.println("<input type='password' name='p' value='" + String(pass) + "' placeholder='Password' required>"); // [cite: 90]
  client.println("<input type='password' name='a' value='" + String(admin_password) + "' placeholder='Admin Master Password' required>"); // [cite: 91]
  client.println("<input type='text' name='ti' value='" + String(proxmox_log_server) + "' placeholder='Backend Address / Domain Link' required>"); // [cite: 92]
  client.println("<input type='text' name='tp' value='" + String(proxmox_log_port) + "' placeholder='Port Target' required>"); // [cite: 93]
  client.println("<input type='submit' style='background:#5c33cf;font-weight:bold;cursor:pointer;' value='Save Infrastructure Settings'></form></div></body></html>"); // [cite: 93]
  delay(50); client.stop(); // [cite: 93]
} // [cite: 94]

void handleWebServer() { // [cite: 94]
  WiFiClient client = server.available(); // [cite: 94]
  if (!client) return; // [cite: 94]
  String reqHeader = ""; // [cite: 94]
  unsigned long webTimeout = millis() + 200;  // [cite: 95]
  while (client.connected() && millis() < webTimeout) { // [cite: 95]
    if (client.available()) { // [cite: 95]
        char c = client.read(); // [cite: 95]
        reqHeader += c; // [cite: 96]
        if (c == '\n') break; // [cite: 96]
    } // [cite: 96]
  } // [cite: 96]

  if (reqHeader.indexOf("GET /api/forgot_password") != -1) { // [cite: 96]
    long tokenNum = random(100000, 999999); // [cite: 96]
    sprintf(temporary_password, "%ld", tokenNum); // [cite: 97]
    hasTemporaryPassword = true; // [cite: 97]
    addLog("RESET: Wygenerowano haslo tymczasowe [" + String(temporary_password) + "]"); // [cite: 97]
    globalDisplayInfo = "Klucz tymczasowy wyslany"; // [cite: 97]
    tone(BUZZER_PIN, 1400, 400); // [cite: 98]
    client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\nOK"); // [cite: 98]
    delay(1); client.stop(); return; // [cite: 98]
  } // [cite: 99]

  if (failedLoginAttempts >= 5 && millis() < lockoutEndTime) { // [cite: 99]
    client.println("HTTP/1.1 403 Forbidden\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n[ALERT] LOCKOUT ACTIVE."); // [cite: 99]
    delay(1); client.stop(); return; // [cite: 100]
  }

  String attemptedPass = ""; // [cite: 100]
  int passPos = reqHeader.indexOf("pass="); // [cite: 100]
  if (passPos != -1) { // [cite: 101]
    int spacePos = reqHeader.indexOf(" ", passPos); // [cite: 101]
    int ampPos = reqHeader.indexOf("&", passPos); // [cite: 101]
    int endPos = spacePos; // [cite: 102]
    if (ampPos != -1 && ampPos < spacePos) { // [cite: 102]
      endPos = ampPos; // [cite: 102]
    } // [cite: 103]
    attemptedPass = reqHeader.substring(passPos + 5, endPos); // [cite: 103]
  }

  String decodedAttempt = urlDecode(attemptedPass); // [cite: 103]
  bool authPermanent = (passPos != -1 && decodedAttempt == String(admin_password)); // [cite: 104]
  bool authTemporary = (passPos != -1 && hasTemporaryPassword && decodedAttempt == String(temporary_password)); // [cite: 105]
  bool isAuthenticated = (authPermanent || authTemporary); // [cite: 105]
  bool isApiRequest = (reqHeader.indexOf("/api/") != -1); // [cite: 106]
  if (passPos != -1 && isApiRequest) { // [cite: 106]
    if (!isAuthenticated && decodedAttempt.length() > 0) { // [cite: 106]
      failedLoginAttempts++; // [cite: 106]
      if (failedLoginAttempts >= 5) { // [cite: 107]
        lockoutEndTime = millis() + 300000;  // [cite: 107]
        addLog("ALARM: Atak BruteForce!"); // [cite: 107]
      } // [cite: 108]
    } else if (isAuthenticated) { // [cite: 108]
      failedLoginAttempts = 0; // [cite: 108]
    } // [cite: 109]
  }

  if (reqHeader.indexOf("/api/update") != -1) { // [cite: 109]
    addLog("OTA REQUEST DETECTED"); // [cite: 109]
    if (!isAuthenticated) { // [cite: 110]
      client.println("HTTP/1.1 401 Unauthorized"); // [cite: 110]
      client.println("Connection: close\r\n"); // [cite: 110]
      client.stop(); // [cite: 110]
      return; // [cite: 111]
    }
    updateDisplay("OTA UPDATE", "Receiving firmware..."); // [cite: 111]
    tone(BUZZER_PIN, 1500, 100); // [cite: 111]
    String fullHeader = reqHeader; // [cite: 111]
    unsigned long headerDeadline = millis() + 5000; // [cite: 112]
    while (millis() < headerDeadline) { // [cite: 112]
        while (client.available()) { // [cite: 112]
            char c = client.read(); // [cite: 112]
            fullHeader += c; // [cite: 113]
            if (fullHeader.endsWith("\r\n\r\n")) { // [cite: 113]
                goto HEADER_COMPLETE; // [cite: 113]
            } // [cite: 114]
        } // [cite: 114]
    } // [cite: 114]
HEADER_COMPLETE:
    int contentLength = 0; // [cite: 114]
    int clPos = fullHeader.indexOf("Content-Length:"); // [cite: 115]
    if (clPos != -1) { // [cite: 115]
        int clEnd = fullHeader.indexOf("\r\n", clPos); // [cite: 115]
        String lengthStr = fullHeader.substring(clPos + 15, clEnd); // [cite: 116]
        lengthStr.trim(); // [cite: 116]
        contentLength = lengthStr.toInt(); // [cite: 116]
    } // [cite: 117]
    if (contentLength <= 0) { // [cite: 117]
        client.println("HTTP/1.1 400 Bad Request\r\nConnection: close\r\n"); // [cite: 117]
        client.stop(); // [cite: 118]
        addLog("OTA FAILED: Invalid Content-Length"); // [cite: 118]
        return; // [cite: 118]
    }
    addLog("OTA START. SIZE: " + String(contentLength)); // [cite: 118]
    
    // 🌟 RECOVERY DEFENSIVE ROUTINE WIPE (PREVENTS BRICKED ALLOCATIONS)
    InternalStorage.close(); // [cite: 123]
    if (!InternalStorage.open(contentLength)) { // // 
        client.println("HTTP/1.1 500 Internal Error\r\nConnection: close\r\n"); // 
        client.stop(); // 
        addLog("OTA FAILED: InternalStorage.open()"); // 
        return; // [cite: 120]
    }
    uint32_t receivedBytes = 0; // [cite: 120]
    unsigned long receiveDeadline = millis() + 120000; // [cite: 120]
    while (receivedBytes < contentLength && millis() < receiveDeadline) { // [cite: 121]
        while (client.available()) { // [cite: 121]
            uint8_t b = client.read(); // [cite: 121]
            InternalStorage.write(b); // // [cite: 122]
            receivedBytes++; // [cite: 122]
            receiveDeadline = millis() + 120000; // [cite: 122]
            if (receivedBytes >= contentLength) break; // [cite: 122]
        } // [cite: 123]
        delay(1); // [cite: 123]
    } // [cite: 123]
    InternalStorage.close(); // [cite: 123]
    if (receivedBytes != contentLength) { // [cite: 124]
        client.println("HTTP/1.1 408 Timeout\r\nConnection: close\r\n"); // [cite: 124]
        client.stop(); // [cite: 124]
        addLog("OTA FAILED: Bytes verification mismatch"); // [cite: 125]
        return; // [cite: 125]
    }
    client.println("HTTP/1.1 200 OK"); // [cite: 125]
    client.println("Content-Type: application/json"); // [cite: 125]
    client.println("Connection: close\r\n"); // [cite: 125]
    client.println("{\"success\":true}"); // [cite: 125]
    delay(100); // [cite: 125]
    client.stop(); // [cite: 125]
    addLog("OTA COMPLETE. APPLYING CORE REWRITE..."); // [cite: 126]
    tone(BUZZER_PIN, 1800, 300); delay(100); tone(BUZZER_PIN, 2200, 500); // [cite: 126]
    delay(1000); // [cite: 126]
    InternalStorage.apply(); //  // [cite: 126]
    return; // [cite: 127]
  } // [cite: 127]

  if (reqHeader.indexOf("GET /api/data") != -1) { // [cite: 127]
    client.println("HTTP/1.1 200 OK"); // [cite: 127]
    client.println("Content-Type: application/json"); // [cite: 127]
    client.println("Connection: close\r\n"); // [cite: 127]
    if (!isAuthenticated) { // [cite: 128]
      client.println("{\"auth\":false}"); // [cite: 128]
    } else { // [cite: 128]
      client.print("{\"auth\":true,\"mode\":\""); // [cite: 128]
      client.print(learningMode ? "Uczenie" : "Czuwanie"); // [cite: 128]
      client.print("\",\"pending\":\""); client.print(pendingUsername); // [cite: 128]
      client.print("\",\"lock\":"); // [cite: 128]
      client.print(doorOpen ? "true" : "false"); // // [cite: 129]
      client.print(",\"total\":"); client.print(totalCards); // [cite: 129]
      client.print(",\"version\":\""); client.print(app_version); client.print("\""); // [cite: 129]
      client.print(",\"users\":["); // [cite: 129]
      for (int i = 0; i < totalCards; i++) { // [cite: 130]
        client.print("{\"idx\":"); client.print(i); // [cite: 130]
        client.print(",\"name\":\""); client.print(users[i].name); // // [cite: 131]
        client.print("\",\"active\":"); client.print(isCardActive[i] ? "true" : "false"); // [cite: 131]
        client.print(",\"uid\":\""); // [cite: 132]
        for(byte j=0; j<4; j++) { // [cite: 132]
          if(users[i].uid[j]<0x10) client.print("0"); // [cite: 132]
          client.print(users[i].uid[j], HEX); // [cite: 132]
          if(j<3) client.print(" "); // [cite: 132]
        } // [cite: 132]
        client.print("\"}"); // [cite: 133]
        if (i < totalCards - 1) client.print(","); // [cite: 133]
      } // [cite: 133]
      client.print("],\"logs\":["); // [cite: 133]
      for (int i = logCount - 1; i >= 0; i--) { // [cite: 134]
        client.print("\"[" + lastActions[i].time + "] " + lastActions[i].msg + "\""); // // [cite: 134]
        if (i > 0) client.print(","); // [cite: 135]
      } // [cite: 135]
      client.print("],\"ssid\":\""); client.print(ssid); // [cite: 135]
      client.print("\",\"admin_pass\":\""); client.print(admin_password); // [cite: 135]
      client.print("\"}"); // [cite: 135]
    } // // [cite: 136]
    delay(1); client.stop(); return; // [cite: 136]
  } // [cite: 136]

  if (isAuthenticated) { // [cite: 136]
    if (reqHeader.indexOf("/api/unlock") != -1) { // [cite: 136]
      if (!doorOpen) openDoor("Panel API"); // [cite: 136]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 137]
      delay(1); client.stop(); return; // [cite: 137]
    }  // [cite: 137]
    else if (reqHeader.indexOf("/api/toggle_learn") != -1) { // [cite: 137]
      learningMode = !learningMode; // [cite: 137]
      autoExitLearn = false;  // [cite: 138]
      if (learningMode) { // [cite: 138]
        if (reqHeader.indexOf("username=") != -1) { // [cite: 138]
          int startIdx = reqHeader.indexOf("username=") + 9; // [cite: 138]
          int endIdx = reqHeader.indexOf(" ", startIdx); // [cite: 139]
          if (reqHeader.indexOf("&", startIdx) != -1 && reqHeader.indexOf("&", startIdx) < endIdx) { // [cite: 139]
            endIdx = reqHeader.indexOf("&", startIdx); // [cite: 139]
          } // // [cite: 140]
          pendingUsername = reqHeader.substring(startIdx, endIdx); // [cite: 140]
          pendingUsername.replace("+", " "); // [cite: 140]
          if(pendingUsername.length() == 0) pendingUsername = "Nowy Uzytkownik"; // [cite: 141]
        } // [cite: 141]
        forceHardwareRFIDReset(); // [cite: 141]
        globalAnimFrame = 0; // [cite: 141]
        addLog("Tryb Ucz. [" + pendingUsername + "]"); // [cite: 142]
        tone(BUZZER_PIN, 1500, 300); // [cite: 142]
      } else { // [cite: 143]
        addLog("Stop Ucz: Panel API"); // [cite: 143]
        tone(BUZZER_PIN, 800, 300); // [cite: 143]
      } // // [cite: 144]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 144]
      delay(1); client.stop(); return; // [cite: 144]
    }  // // [cite: 145]
    else if (reqHeader.indexOf("/api/delete_user") != -1) { // [cite: 145]
      int idxPos = reqHeader.indexOf("idx="); // [cite: 145]
      if (idxPos != -1) { // [cite: 146]
        int targetIdx = reqHeader.substring(idxPos + 4, reqHeader.indexOf(" ", idxPos)).toInt(); // [cite: 146]
        if (targetIdx >= 0 && targetIdx < totalCards) { // [cite: 147]
          String deletedName = String(users[targetIdx].name); // [cite: 147]
          deleteUser(targetIdx); // [cite: 148]
          addLog("Usunieto: " + deletedName); // [cite: 148]
          tone(BUZZER_PIN, 600, 400); // [cite: 148]
        } // [cite: 148]
      } // [cite: 148]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 148]
      delay(1); client.stop(); return; // [cite: 149]
    } // [cite: 149]
    else if (reqHeader.indexOf("/api/rename_user") != -1) { // [cite: 149]
      int idxPos = reqHeader.indexOf("idx="); // [cite: 149]
      int namePos = reqHeader.indexOf("name="); // [cite: 150]
      if (idxPos != -1 && namePos != -1) { // [cite: 150]
        int targetIdx = reqHeader.substring(idxPos + 4, reqHeader.indexOf("&", idxPos)).toInt(); // [cite: 150]
        String newName = reqHeader.substring(namePos + 5, reqHeader.indexOf(" ", namePos)); // [cite: 151]
        newName.replace("+", " "); // [cite: 151]
        if (targetIdx >= 0 && targetIdx < totalCards && newName.length() > 0) { // [cite: 152]
          memset(users[targetIdx].name, 0, 16); // [cite: 152]
          newName.toCharArray(users[targetIdx].name, 16); // [cite: 153]
          EEPROM.put(10 + (targetIdx * sizeof(User)), users[targetIdx]);  // [cite: 153]
          addLog("Zmiana nazwy slot [" + String(targetIdx) + "]"); // [cite: 153]
          tone(BUZZER_PIN, 1200, 150); // [cite: 153]
        } // // [cite: 154]
      } // [cite: 154]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 154]
      delay(1); client.stop(); return; // [cite: 154]
    } // [cite: 155]
    else if (reqHeader.indexOf("/api/toggle_user_active") != -1) { // [cite: 155]
      int idxPos = reqHeader.indexOf("idx="); // [cite: 155]
      if (idxPos != -1) { // [cite: 156]
        int targetIdx = reqHeader.substring(idxPos + 4, reqHeader.indexOf(" ", idxPos)).toInt(); // [cite: 156]
        if (targetIdx >= 0 && targetIdx < totalCards) { // [cite: 157]
          isCardActive[targetIdx] = !isCardActive[targetIdx]; // [cite: 157]
          EEPROM.write(220 + targetIdx, isCardActive[targetIdx] ? 0x01 : 0x00);  // [cite: 158]
          addLog(isCardActive[targetIdx] ? "Aktywowano: " + String(users[targetIdx].name) : "Zablokowano: " + String(users[targetIdx].name)); // [cite: 158]
          tone(BUZZER_PIN, 1100, 150); // [cite: 159]
        } // [cite: 159]
      } // [cite: 159]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 159]
      delay(1); // [cite: 159]
      client.stop(); return; // [cite: 160]
    } // [cite: 160]
    else if (reqHeader.indexOf("/api/clear_logs") != -1) { // [cite: 160]
      int tPos = reqHeader.indexOf("time="); // [cite: 160]
      if (tPos != -1) { // [cite: 161]
        int spaceIdx = reqHeader.indexOf(" ", tPos); // [cite: 161]
        String cutoffVal = reqHeader.substring(tPos + 5, spaceIdx); // [cite: 162]
        cutoffVal.replace("%3A", ":");  // [cite: 162]
        if (cutoffVal == "all") { // [cite: 162]
          logCount = 0; // [cite: 162]
          addLog("Wyczyszczono caly dziennik"); // [cite: 163]
        } else if (cutoffVal.indexOf(":") != -1) { // [cite: 163]
          int targetH = cutoffVal.substring(0, cutoffVal.indexOf(":")).toInt(); // [cite: 163]
          int targetM = cutoffVal.substring(cutoffVal.indexOf(":") + 1).toInt(); // [cite: 164]
          int targetMinutesWeight = (targetH * 60) + targetM; // [cite: 164]
          int i = 0; // [cite: 164]
          while (i < logCount) { // [cite: 165]
            int logH = lastActions[i].time.substring(0, 2).toInt(); // [cite: 165]
            int logM = lastActions[i].time.substring(3, 5).toInt(); // [cite: 166]
            int logMinutesWeight = (logH * 60) + logM; // [cite: 166]
            if (logMinutesWeight < targetMinutesWeight) { // [cite: 167]
              for (int j = i; j < logCount - 1; j++) { // [cite: 167]
                lastActions[j] = lastActions[j + 1]; // [cite: 167]
              } //  // [cite: 168]
              logCount--; // [cite: 168]
            } else { i++; // [cite: 168]
            } // // [cite: 169]
          } // [cite: 169]
          addLog("Usunieto logi starsze niz " + cutoffVal); // [cite: 169]
        } // // [cite: 170]
        tone(BUZZER_PIN, 900, 150); // [cite: 170]
      } // // [cite: 171]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 171]
      delay(1); client.stop(); return; // [cite: 171]
    } // [cite: 172]
    else if (reqHeader.indexOf("/api/save_settings") != -1) { // [cite: 172]
      int sIdx = reqHeader.indexOf("s=") + 2; // [cite: 172]
      int pIdx = reqHeader.indexOf("&p=") + 3; // [cite: 173]
      int aIdx = reqHeader.indexOf("&a=") + 3; // [cite: 173]
      String nSSID = reqHeader.substring(sIdx, reqHeader.indexOf("&p=")); // [cite: 173]
      String nPass = reqHeader.substring(pIdx, reqHeader.indexOf("&a=")); // [cite: 174]
      int nextAmp = reqHeader.indexOf("&", aIdx); // [cite: 174]
      int spaceIdx = reqHeader.indexOf(" ", aIdx); // [cite: 174]
      int endPortPos = (nextAmp != -1 && nextAmp < spaceIdx) ? nextAmp : spaceIdx; // [cite: 175]
      String nAdmin = reqHeader.substring(aIdx, endPortPos); // [cite: 175]
      String decSSID = urlDecode(nSSID); String decPass = urlDecode(nPass); String decAdmin = urlDecode(nAdmin); // [cite: 176]
      saveConfiguration(decSSID, decPass, decAdmin, proxmox_log_server, proxmox_log_port, telemetryEnabled); // [cite: 176]
      addLog("Zapisano ustawienia"); // [cite: 176]
      client.println("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nOK"); // [cite: 177]
      delay(1); client.stop(); return; // [cite: 177]
    } // [cite: 177]
  } // [cite: 177]
} // [cite: 177]

void handleOnlineInstallerServer() { // [cite: 177]
  WiFiClient client = server.available();  // [cite: 177]
  if (!client) return; // [cite: 177]
  String reqHeader = ""; unsigned long webTimeout = millis() + 250; // [cite: 178]
  while (client.connected() && millis() < webTimeout) { if (client.available()) { char c = client.read(); reqHeader += c; // [cite: 179]
  if (c == '\n') break; } } // // [cite: 180]
  while (client.available()) { client.read(); } // [cite: 180]
  String expectedAuthSignature = "pass=" + String(admin_password); // [cite: 180]
  if (reqHeader.indexOf("GET /installer") != -1 && reqHeader.indexOf(expectedAuthSignature) != -1) { // [cite: 181]
    client.println("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nConnection: close\r\n"); // [cite: 181]
    client.println("<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>"); // [cite: 182]
    client.println("<style>body{background:#121212;color:#fff;font-family:sans-serif;padding:20px;} .box{background:#1e1e1e;padding:20px;border-radius:10px;max-width:400px;margin:20px auto;} input{display:block;width:92%;padding:12px;margin:12px auto;background:#2d2d2d;color:#fff;border:1px solid #444;border-radius:6px;}</style></head><body>"); // [cite: 182]
    client.println("<h2 style='text-align:center;'>⚙       Online Installer Portal</h2><div class='box'><form method='GET' action='/save_setup'>"); // [cite: 183]
    client.println("<input type='text' name='s' value='" + String(ssid) + "' placeholder='SSID Wi-Fi' required>"); // [cite: 184]
    client.println("<input type='password' name='p' value='" + String(pass) + "' placeholder='Password' required>"); // [cite: 185]
    client.println("<input type='password' name='a' value='" + String(admin_password) + "' placeholder='Admin Master Password' required>"); // [cite: 186]
    client.println("<input type='text' name='ti' value='" + String(proxmox_log_server) + "' placeholder='Backend Address / Domain Link' required>"); // [cite: 187]
    client.println("<input type='text' name='tp' value='" + String(proxmox_log_port) + "' placeholder='Port Target' required>"); // [cite: 188]
    client.println("<input type='submit' style='background:#5c33cf;font-weight:bold;cursor:pointer;' value='Update & Reboot Hardware'></form></div></body></html>"); // [cite: 188]
    delay(50); client.stop(); // [cite: 188]
    return; // [cite: 189]
  } // [cite: 189]
} // [cite: 189]

void executeCloudSynchronization() { // [cite: 189]
  if (strlen(proxmox_log_server) < 4) return; // [cite: 189]
  WiFiClient httpCheck;  // [cite: 189]
  httpCheck.setTimeout(250); // [cite: 189]
  if (!httpCheck.connect(proxmox_log_server, proxmox_log_port)) { // [cite: 190]
    if (millis() - lastSuccessfulPollTime > 30000) { // [cite: 190]
      isOfflineStandby = true; // [cite: 190]
      displayProvisioningInstructions("ERR: CLOUD LOSS");  // // [cite: 191]
      WiFi.disconnect();  // [cite: 191]
      delay(500);  // [cite: 191]
      WiFi.beginAP("ZAMEK_SETUP");  // [cite: 191]
      server.begin(); // [cite: 191]
    } // [cite: 191]
    return; // [cite: 191]
  } // [cite: 191]
  lastSuccessfulPollTime = millis(); // [cite: 191]
  String pollPath = "/api/hardware/poll?version=" + urlEncode(String(app_version)); // [cite: 192]
  httpCheck.println("GET " + pollPath + " HTTP/1.1"); // [cite: 192]
  httpCheck.print("Host: "); httpCheck.println(proxmox_log_server); // [cite: 192]
  httpCheck.println("Connection: close\r\n"); // [cite: 192]
  unsigned long deadline = millis() + 300;  // [cite: 193]
  String payloadResponse = ""; // [cite: 193]
  while ((httpCheck.available() || httpCheck.connected()) && millis() < deadline) { // [cite: 194]
    if (httpCheck.available()) {  // [cite: 194]
      char c = httpCheck.read(); // [cite: 194]
      payloadResponse += c;  // [cite: 195]
    } // [cite: 195]
  } // [cite: 195]
  httpCheck.stop(); // [cite: 195]
  
  // 🌟 CLOUD SIGNAL RESOLUTION INTERACTION DECODE
  bool serverUnlockSignal = (payloadResponse.indexOf("\"unlock\":true") != -1);
  bool serverLearnSignal  = (payloadResponse.indexOf("\"learn\":true") != -1);

  if (serverUnlockSignal) { // [cite: 195]
    if (!doorOpen) openDoor("Zdalne Wywolanie"); // [cite: 196]
  } // [cite: 196]
  if (serverLearnSignal) { // [cite: 196]
    learningMode = true; // [cite: 196]
    int userStart = payloadResponse.indexOf("\"username\":\"");  // [cite: 197]
    int userEnd = payloadResponse.indexOf("\"", userStart + 12); // [cite: 197]
    if (userStart > -1 && userEnd > userStart) { // [cite: 198]
      pendingUsername = payloadResponse.substring(userStart + 12, userEnd); // [cite: 198]
    } // [cite: 199]
  } else {  // [cite: 199]
    learningMode = false; // [cite: 199]
  } // [cite: 200]
} // [cite: 200]

void transmitCardPayloadToCloud(String uidStr, byte* rawUid, bool runRegister) { // [cite: 200]
  if (strlen(proxmox_log_server) < 4) return; // [cite: 200]
  WiFiClient httpPost;  // [cite: 200]
  httpPost.setTimeout(400); // [cite: 200]
  if (!httpPost.connect(proxmox_log_server, proxmox_log_port)) return;  // [cite: 201]
  String endpoint = runRegister ? "/api/hardware/register" : "/api/hardware/scan"; // [cite: 201]
  String postData = runRegister ? // [cite: 201]
  "{\"uid\":\"" + uidStr + "\",\"name\":\"" + pendingUsername + "\"}" : "{\"uid\":\"" + uidStr + "\"}"; // [cite: 202]
  httpPost.println("POST " + endpoint + " HTTP/1.1");  // [cite: 203]
  httpPost.print("Host: "); httpPost.println(proxmox_log_server); // [cite: 203]
  httpPost.println("Content-Type: application/json");  // [cite: 203]
  httpPost.print("Content-Length: "); httpPost.println(postData.length()); // [cite: 203]
  httpPost.println("Connection: close\r\n");  // [cite: 203]
  httpPost.print(postData); // [cite: 203]
  unsigned long deadline = millis() + 400;  // [cite: 204]
  String payloadResponse = ""; // [cite: 204]
  while ((httpPost.available() || httpPost.connected()) && millis() < deadline) { // [cite: 205]
    if (httpPost.available()) {  // [cite: 205]
      char c = httpPost.read(); // [cite: 205]
      payloadResponse += c;  // [cite: 206]
    } // [cite: 206]
  } // [cite: 206]
  httpPost.stop(); // [cite: 206]
} // [cite: 206]

void setup() { // [cite: 206]
  Serial.begin(9600);  // [cite: 206]
  delay(1500);  // [cite: 206]
  pinMode(BUTTON_PIN, INPUT_PULLUP); // [cite: 206]
  loadConfiguration();  // [cite: 206]
  loadCards(); // [cite: 206]
  if (digitalRead(BUTTON_PIN) == LOW) {  // [cite: 207]
    delay(2000); // [cite: 207]
    if (digitalRead(BUTTON_PIN) == LOW) {  // [cite: 208]
      factoryResetSettings();  // [cite: 208]
      Serial.println("[FACTORY RESET COMPLETE]"); // [cite: 208]
    }  // [cite: 209]
  } // [cite: 209]
  pinMode(RELAY_PIN, OUTPUT);  // [cite: 209]
  pinMode(LED_GREEN, OUTPUT);  // [cite: 209]
  pinMode(LED_RED, OUTPUT); // [cite: 209]
  pinMode(RST_PIN, OUTPUT);  // [cite: 209]
  digitalWrite(RST_PIN, HIGH);  // [cite: 209]
  delay(50); // [cite: 209]
  digitalWrite(RELAY_PIN, HIGH);  // [cite: 209]
  digitalWrite(LED_GREEN, LOW); // [cite: 209]
  digitalWrite(LED_RED, LOW);  // --- FIX: Dark on Standby ---
  SPI.begin();  // [cite: 210]
  RTC.begin();  // [cite: 210]
  randomSeed(analogRead(0));  // [cite: 210]
  delay(300);  // [cite: 210]
  display.begin(0x3C, true);  // [cite: 210]
  display.clearDisplay(); // [cite: 210]

  if (provisioningMode) { // [cite: 210]
    displayProvisioningInstructions("");  // [cite: 210]
    WiFi.beginAP("ZAMEK_SETUP");  // [cite: 210]
    server.begin(); // [cite: 210]
    tone(BUZZER_PIN, 600, 250);  // [cite: 211]
    delay(300);  // [cite: 211]
    tone(BUZZER_PIN, 600, 250); // [cite: 211]
    unsigned long lastSetupTick = 0;  // [cite: 211]
    bool alternateState = false; // [cite: 211]
    while (true) {  // [cite: 212]
      handleProvisioningServer(); // [cite: 212]
      if (millis() - lastSetupTick > 400) { // [cite: 213]
        lastSetupTick = millis();  // [cite: 213]
        globalAnimFrame++;  // [cite: 213]
        renderSystemUI(); // [cite: 213]
        alternateState = !alternateState; // [cite: 214]
        digitalWrite(LED_RED, alternateState ? HIGH : LOW);  // [cite: 214]
        digitalWrite(LED_GREEN, alternateState ? LOW : HIGH); // [cite: 214]
      } // [cite: 215]
      delay(10);  // [cite: 215]
    } // [cite: 215]
  } // [cite: 215]

  updateDisplay("Wi-Fi: Laczenie...", "Proba: 1/3 [....]");  // [cite: 215]
  WiFi.begin(ssid, pass); // [cite: 215]
  unsigned long startAttempt = millis();  // [cite: 216]
  int counter = 0; // [cite: 216]
  while (WiFi.status() != WL_CONNECTED && millis() - startAttempt < 12000) { // [cite: 216]
    delay(500); // [cite: 216]
    counter++; // [cite: 217]
    if (counter == 8) updateDisplay("Wi-Fi: Laczenie...", "Proba: 2/3 [======]"); // [cite: 217]
    if (counter == 16) updateDisplay("Wi-Fi: Laczenie...", "Proba: 3/3 [........]"); // [cite: 217]
  } // [cite: 218]

  if (WiFi.status() == WL_CONNECTED) { // [cite: 218]
    timeClient.begin();  // [cite: 218]
    timeClient.update(); // [cite: 218]
    unsigned long epochTime = timeClient.getEpochTime();  // [cite: 218]
    RTCTime localTime(epochTime);  // [cite: 218]
    RTC.setTime(localTime); // [cite: 218]
    forceHardwareRFIDReset();  // [cite: 219]
    lastSuccessfulPollTime = millis();  // [cite: 219]
    server.begin(); // [cite: 219]
    updateDisplay("Gotowy", WiFi.localIP().toString());  // [cite: 219]
    addLog("System online"); // [cite: 219]
    tone(BUZZER_PIN, 800, 100);  delay(120);  // [cite: 219]
    tone(BUZZER_PIN, 1000, 100); delay(120);  // [cite: 219]
    tone(BUZZER_PIN, 1300, 120); // [cite: 219]
    delay(140);  // [cite: 220]
    tone(BUZZER_PIN, 1600, 300); // [cite: 220]
  } else { // [cite: 220]
    isOfflineStandby = true;  // [cite: 220]
    forceHardwareRFIDReset();  // [cite: 220]
    displayProvisioningInstructions("ERR: CONN TIMEOUT"); // [cite: 220]
    WiFi.disconnect();  // [cite: 220]
    delay(500);  // [cite: 220]
    WiFi.beginAP("ZAMEK_SETUP"); // [cite: 220]
    server.begin();  // [cite: 221]
    tone(BUZZER_PIN, 300, 600);  // [cite: 221]
    lastWifiRetryTime = millis();  // [cite: 221]
  } // [cite: 221]
  lastRfidWatchdogTime = millis();  // [cite: 222]
  lastFrameTick = millis(); // [cite: 222]
} // [cite: 222]

void loop() {  // [cite: 222]
  if (millis() - lastFrameTick > 80) {  // [cite: 222]
    lastFrameTick = millis();  // [cite: 222]
    globalAnimFrame++;  // [cite: 222]
    renderSystemUI(); // [cite: 222]
  } // [cite: 223]

  if (!doorOpen && !learningMode && (millis() - lastRfidWatchdogTime > 120000)) { // [cite: 223]
    lastRfidWatchdogTime = millis();  // [cite: 223]
    forceHardwareRFIDReset(); // [cite: 223]
  } // [cite: 224]

  if (isOfflineStandby) { // [cite: 224]
    handleProvisioningServer(); // [cite: 224]
    if (millis() - lastWifiRetryTime > 60000) { // [cite: 224]
      lastWifiRetryTime = millis(); // [cite: 224]
      updateDisplay("RESCUE WATCHDOG", "Sprawdzam Wi-Fi...");  // [cite: 225]
      WiFi.begin(ssid, pass); // [cite: 225]
      unsigned long checkStart = millis(); // [cite: 225]
      while (WiFi.status() != WL_CONNECTED && millis() - checkStart < 6000) {  // [cite: 226]
        delay(200); // [cite: 226]
      } // [cite: 227]
      if (WiFi.status() == WL_CONNECTED) { // [cite: 227]
        isOfflineStandby = false; // [cite: 227]
        timeClient.begin();  // [cite: 228]
        timeClient.update(); // [cite: 228]
        unsigned long epochTime = timeClient.getEpochTime();  // [cite: 228]
        RTCTime localTime(epochTime);  // [cite: 228]
        RTC.setTime(localTime); // [cite: 228]
        server.begin();  // [cite: 228]
        updateDisplay("Gotowy", WiFi.localIP().toString());  // [cite: 229]
        addLog("Polaczenie Wi-Fi przywrocone"); // [cite: 229]
        lastSuccessfulPollTime = millis(); // [cite: 229]
        tone(BUZZER_PIN, 1200, 150); delay(100); tone(BUZZER_PIN, 1500, 150); // [cite: 229]
      } else { // [cite: 229]
        WiFi.disconnect();  // [cite: 229]
        delay(1000);  // [cite: 229]
        WiFi.beginAP("ZAMEK_SETUP"); // [cite: 229]
        delay(500);  // [cite: 230]
        server.begin();  // [cite: 230]
        displayProvisioningInstructions("ERR: REKONEKCJA FAIL"); // [cite: 230]
      } // [cite: 230]
    } // [cite: 230]
  } else { // [cite: 230]
    handleWebServer(); // [cite: 230]
    if (WiFi.status() == WL_CONNECTED && millis() - lastPollTime > 1000) {  // [cite: 231]
      lastPollTime = millis(); // [cite: 231]
      executeCloudSynchronization();  // [cite: 232]
    } // [cite: 232]
  } // [cite: 232]

  if (rfidResetPending && !doorOpen && (millis() - lastScanTime > 1000)) { // [cite: 232]
    forceHardwareRFIDReset(); // [cite: 232]
    rfidResetPending = false;  // [cite: 233]
    if (learningMode) {  // [cite: 233]
      globalAnimFrame = 0; // [cite: 233]
    } else {  // [cite: 234]
      globalDisplayInfo = ""; // [cite: 234]
    }  // [cite: 235]
  } // [cite: 235]

  if (learningMode) { // [cite: 235]
    if (millis() % 500 < 250) {  // [cite: 235]
      digitalWrite(LED_RED, HIGH); // [cite: 235]
      digitalWrite(LED_GREEN, LOW);  // [cite: 236]
    } else {  // [cite: 236]
      digitalWrite(LED_RED, LOW);  // [cite: 236]
      digitalWrite(LED_GREEN, HIGH); // [cite: 236]
    } // [cite: 237]
  } else if (!doorOpen) { // [cite: 237]
    if (failedLoginAttempts >= 5 && millis() < lockoutEndTime) { // [cite: 237]
      digitalWrite(LED_RED, millis() % 200 < 100 ? HIGH : LOW); // [cite: 237]
      digitalWrite(LED_GREEN, LOW); // [cite: 238]
    } else { // [cite: 238]
      if (isOfflineStandby) {  // [cite: 238]
        digitalWrite(LED_RED, millis() % 1000 < 150 ? LOW : HIGH);  // [cite: 239]
      } else {  // [cite: 239]
        digitalWrite(LED_RED, LOW);  // --- Dark on Standby Mode ---
      }  // [cite: 240]
      digitalWrite(LED_GREEN, LOW); // [cite: 240]
    } // [cite: 240]
  } // [cite: 240]

  if (!rfidResetPending && !doorOpen && (failedLoginAttempts < 5 || millis() > lockoutEndTime) && rfid.PICC_IsNewCardPresent() && rfid.PICC_ReadCardSerial()) { // [cite: 240]
    lastRfidWatchdogTime = millis(); // [cite: 240]
    String uidStr = ""; // [cite: 241]
    for (byte i = 0; i < rfid.uid.size; i++) { // [cite: 241]
      if (rfid.uid.uidByte[i] < 0x10) uidStr += "0"; // [cite: 241]
      uidStr += String(rfid.uid.uidByte[i], HEX);  // [cite: 242]
      if (i < rfid.uid.size - 1) uidStr += " "; // [cite: 242]
    } // [cite: 242]
    uidStr.toUpperCase(); // [cite: 242]
    transmitCardPayloadToCloud(uidStr, rfid.uid.uidByte, learningMode); // [cite: 243]

    if (learningMode) { // [cite: 243]
      saveNewCard(rfid.uid.uidByte, pendingUsername); // [cite: 243]
      addLog("Przypisano: " + pendingUsername + " [" + uidStr + "]");  // [cite: 244]
      globalAnimFrame = 0;  // [cite: 244]
      globalDisplayInfo = "DODANO KARTE";  // [cite: 244]
      digitalWrite(LED_RED, LOW); // [cite: 244]
      digitalWrite(LED_GREEN, HIGH); // [cite: 245]
      tone(BUZZER_PIN, 1000, 150); delay(150);  // [cite: 245]
      tone(BUZZER_PIN, 1500, 150); delay(150);  // [cite: 245]
      tone(BUZZER_PIN, 2000, 400); // [cite: 245]
      if (autoExitLearn) {  // [cite: 246]
        learningMode = false;  // [cite: 246]
        autoExitLearn = false; // [cite: 246]
      } // [cite: 247]
    } else { // [cite: 247]
      bool valid = false;  // [cite: 247]
      int matchedIndex = -1; // [cite: 247]
      for (int i = 0; i < totalCards; i++) {  // [cite: 248]
        if (memcmp(rfid.uid.uidByte, users[i].uid, 4) == 0) {  // [cite: 248]
          valid = true; // [cite: 248]
          matchedIndex = i;  // [cite: 249]
          break;  // [cite: 249]
        }  // [cite: 249]
      } // [cite: 249]
      if (valid) {  // [cite: 249]
        if (isCardActive[matchedIndex]) {  // [cite: 249]
          openDoor(String(users[matchedIndex].name)); // [cite: 249]
        } else {  // [cite: 250]
          addLog("Odmowa: Zablokowana [" + String(users[matchedIndex].name) + "]"); // [cite: 250]
          digitalWrite(LED_RED, HIGH); delay(600); digitalWrite(LED_RED, LOW);
          tone(BUZZER_PIN, 200, 600);  // [cite: 251]
        }  // [cite: 251]
      } else {  // [cite: 251]
        addLog("Odmowa: Nieznany [" + uidStr + "]"); // [cite: 252]
        digitalWrite(LED_RED, HIGH); delay(500); digitalWrite(LED_RED, LOW);
        tone(BUZZER_PIN, 200, 500);  // [cite: 252]
      } // [cite: 252]
    } // [cite: 252]
    rfid.PICC_HaltA();  // [cite: 252]
    rfidResetPending = true;  // [cite: 252]
    lastScanTime = millis(); // [cite: 252]
  }  // [cite: 253]

  if (digitalRead(BUTTON_PIN) == LOW) { // [cite: 253]
    unsigned long pressTime = millis();  // [cite: 253]
    bool longPressed = false; // [cite: 253]
    while (digitalRead(BUTTON_PIN) == LOW) { // [cite: 254]
      if (millis() - pressTime > 3000) {  // [cite: 254]
        longPressed = true; // [cite: 254]
        learningMode = !learningMode;  // [cite: 255]
        autoExitLearn = true;  // [cite: 255]
        if (learningMode) { // [cite: 255]
          pendingUsername = "Przycisk"; // [cite: 255]
          forceHardwareRFIDReset();  // [cite: 256]
          lastRfidWatchdogTime = millis();  // [cite: 256]
          globalAnimFrame = 0;  // [cite: 256]
          tone(BUZZER_PIN, 1500, 400); // [cite: 256]
        } else {  // [cite: 257]
          globalDisplayInfo = "";  // [cite: 257]
          tone(BUZZER_PIN, 800, 400); // [cite: 257]
        } // [cite: 258]
        while(digitalRead(BUTTON_PIN) == LOW); break; // [cite: 258]
      } // [cite: 258]
      delay(10); // [cite: 258]
    }  // [cite: 259]
    if (!longPressed && (millis() - pressTime > 50)) {  // [cite: 259]
      failedLoginAttempts = 0; // [cite: 259]
      lockoutEndTime = 0;  // [cite: 260]
      lastRfidWatchdogTime = millis();  // [cite: 260]

      WiFiClient buttonLogClient; // [cite: 260]
      buttonLogClient.setTimeout(150); // [cite: 260]
      if (buttonLogClient.connect(proxmox_log_server, proxmox_log_port)) { // [cite: 260]
        buttonLogClient.println("GET /api/hardware/log_button HTTP/1.1"); // [cite: 260]
        buttonLogClient.print("Host: "); buttonLogClient.println(proxmox_log_server); // [cite: 261]
        buttonLogClient.println("Connection: close\r\n"); // [cite: 261]
        buttonLogClient.stop(); // [cite: 261]
      } // [cite: 261]

      openDoor("PRZYCISK"); // [cite: 261]
    } // [cite: 262]
  }  // [cite: 262]

  if (doorOpen && millis() > accessEndTime) {  // [cite: 262]
    doorOpen = false;  // [cite: 262]
    digitalWrite(RELAY_PIN, HIGH);  // [cite: 262]
    delay(100); // [cite: 262]
    forceHardwareRFIDReset();  // [cite: 263]
    lastRfidWatchdogTime = millis();  // [cite: 263]
    rfidResetPending = false;  // [cite: 263]
    globalDisplayInfo = ""; // [cite: 263]
    digitalWrite(LED_GREEN, LOW);  // [cite: 263]
    digitalWrite(LED_RED, LOW);  // --- Dark on Standby ---
  } // [cite: 263]
} // [cite: 263]