[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
board_upload.maximum_size = 262144 
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    miguelbalboa/MFRC522 @ 1.4.11
    jandrassy/ArduinoOTA @ ^1.1.0
    arduino-libraries/NTPClient @ ^3.2.1