[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino

upload_protocol = custom
# Updated flags based on your specific .exe version:
upload_command = "C:/Users/tplewka/Desktop/Personal/OTA/arduinoOTA_windows_amd64/arduinoOTA.exe" -address $UPLOAD_PORT -port 65000 -password password_ota -sketch $SOURCE -v
upload_port = 192.168.0.46
board_upload.maximum_size = 262144 
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    miguelbalboa/MFRC522 @ 1.4.11
    jandrassy/ArduinoOTA @ ^1.1.0
    arduino-libraries/NTPClient @ ^3.2.1