name: Node.js Automated Production Deployment

on:
  push:
    branches:
      - main  # Zmień na master, jeśli tak nazywa się Twoja główna gałąź
    paths:
      - 'Server_app/server.js'
  workflow_dispatch: # Przycisk ręcznego uruchamiania na GitHubie

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup SSH Key on Runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Copy server.js via Verbose Native SCP
        run: |
          echo "📦 Rozpoczynam bezpośredni transfer pliku..."
          scp -v -P 22044 -o StrictHostKeyChecking=no Server_app/server.js ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/smartlock-server/server.js

      - name: Execute Systemd Daemon Restart over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22044
          script: |
            echo "🔄 Plik zaktualizowany. Restartowanie daemona smartlock..."
            systemctl restart smartlock
            echo "✅ Gotowe! Nowy kod produkcyjny został załadowany."